trigger:
  branches:
    include:
      - main  # Cambia según la rama principal de tu repositorio
      - develop  # Rama de desarrollo si la usas

pool:
  vmImage: 'ubuntu-latest'  # Imagen de la máquina virtual

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.2'

- script: |
    dir $(System.DefaultWorkingDirectory)
  displayName: 'List directory contents'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build  # Asegúrate de que tienes un script de build en tu package.json
  displayName: 'Build application'

- script: |
    npm test  # Ejecuta las pruebas si tienes configuradas
  displayName: 'Run tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/dist'  # Cambia a la ruta de tu carpeta de salida de build
    ArtifactName: 'frontend'  # Nombre del artefacto
    publishLocation: 'Container'
